name: Node.js CI

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - uses: docker/login-action@v1
        name: login to azure docker
        with:
          registry: ${{secrets.DOCKER_SERVER}}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Docker build
        run: |
          echo start docker build
          docker build --no-cache -t ${{secrets.DOCKER_SERVER}}/kubernates-node-app:latest .
          echo build completed
      - name: Docker push 🚀🚀🚀
        run: |
          docker push ${{secrets.DOCKER_SERVER}}/kubernates-node-app:latest
          echo docker pushed 🚀🚀🚀
